format shfmt

diff --git a/scripts/gen_proxy b/scripts/gen_proxy
--- a/scripts/gen_proxy
+++ b/scripts/gen_proxy
@@ -21,37 +21,36 @@ mkdir -p "${OUT_DIR}"
 total=$(find . -maxdepth 1 -type f -name "*.${FORMAT}" | wc -l)
 i=1
 
-for input_file in *.${FORMAT}
-do
-  echo "${input_file} ${i}/${total}"
-  random_string=$(tr -dc 'a-zA-Z' </dev/urandom | fold -w 8 | head -n 1)
-  out_file_tmp="${OUT_DIR}/${input_file}${random_string}.tmp.${FORMAT}"
-  out_file="${OUT_DIR}/${input_file}"
+for input_file in *.${FORMAT}; do
+	echo "${input_file} ${i}/${total}"
+	random_string=$(tr -dc 'a-zA-Z' </dev/urandom | fold -w 8 | head -n 1)
+	out_file_tmp="${OUT_DIR}/${input_file}${random_string}.tmp.${FORMAT}"
+	out_file="${OUT_DIR}/${input_file}"
 
-  DIMENSIONS=$(ffprobe -v error -show_entries stream=width,height -of csv=p=0 "$input_file")
-  WIDTH=$(echo "$DIMENSIONS" | cut -d ',' -f 1)
-  HEIGHT=$(echo "$DIMENSIONS" | cut -d ',' -f 2)
+	DIMENSIONS=$(ffprobe -v error -show_entries stream=width,height -of csv=p=0 "$input_file")
+	WIDTH=$(echo "$DIMENSIONS" | cut -d ',' -f 1)
+	HEIGHT=$(echo "$DIMENSIONS" | cut -d ',' -f 2)
 
-  if [ "$WIDTH" -ge "$HEIGHT" ]; then
-    SCALE="scale=1920:-2"
-  else
-    SCALE="scale=-2:1920"
-  fi
+	if [ "$WIDTH" -ge "$HEIGHT" ]; then
+		SCALE="scale=1920:-2"
+	else
+		SCALE="scale=-2:1920"
+	fi
 
-  if ! ffmpeg \
-        -hwaccel auto \
-        -i "${input_file}" \
-        -c:v ${VIDEO_CODEC} \
-        ${VIDEO_OPTIONS} \
-        -vf ${SCALE} \
-        -c:a ${AUDIO_CODEC} \
-        -map_metadata 0 \
-        -loglevel info \
-        "${out_file_tmp}"; then
-    echo "Error: ffmpeg failed"
-    exit 1
-  fi
+	if ! ffmpeg \
+		-hwaccel auto \
+		-i "${input_file}" \
+		-c:v ${VIDEO_CODEC} \
+		${VIDEO_OPTIONS} \
+		-vf ${SCALE} \
+		-c:a ${AUDIO_CODEC} \
+		-map_metadata 0 \
+		-loglevel info \
+		"${out_file_tmp}"; then
+		echo "Error: ffmpeg failed"
+		exit 1
+	fi
 
-  mv "${out_file_tmp}" "${out_file}"
-  ((i++))
+	mv "${out_file_tmp}" "${out_file}"
+	((i++))
 done
diff --git a/scripts/to_av1 b/scripts/to_av1
--- a/scripts/to_av1
+++ b/scripts/to_av1
@@ -9,26 +9,25 @@ mkdir -p "${OUT_DIR}"
 total=$(find . -maxdepth 1 -type f -name '*${FORMAT}' | wc -l)
 i=1
 
-for input_file in *.${FORMAT}
-do
-  echo "${input_file} ${i}/${total}"
-  random_string=$(tr -dc 'a-zA-Z' </dev/urandom | fold -w 8 | head -n 1)
-  out_file_tmp="${OUT_DIR}/${input_file}${random_string}.tmp.${FORMAT}"
-  out_file="${OUT_DIR}/${input_file}"
-  if ! ffmpeg \
-        -hwaccel auto \
-        -i "${input_file}" \
-        -c:v av1_nvenc \
-        -preset p4 \
-        -rc vbr \
-        -c:a ${AUDIO_CODEC} \
-        -map_metadata 0 \
-        -loglevel info \
-        "${out_file_tmp}"; then
-    echo "Error: ffmpeg failed"
-    exit 1
-  fi
+for input_file in *.${FORMAT}; do
+	echo "${input_file} ${i}/${total}"
+	random_string=$(tr -dc 'a-zA-Z' </dev/urandom | fold -w 8 | head -n 1)
+	out_file_tmp="${OUT_DIR}/${input_file}${random_string}.tmp.${FORMAT}"
+	out_file="${OUT_DIR}/${input_file}"
+	if ! ffmpeg \
+		-hwaccel auto \
+		-i "${input_file}" \
+		-c:v av1_nvenc \
+		-preset p4 \
+		-rc vbr \
+		-c:a ${AUDIO_CODEC} \
+		-map_metadata 0 \
+		-loglevel info \
+		"${out_file_tmp}"; then
+		echo "Error: ffmpeg failed"
+		exit 1
+	fi
 
-  mv "${out_file_tmp}" "${out_file}"
-  ((i++))
+	mv "${out_file_tmp}" "${out_file}"
+	((i++))
 done
diff --git a/scripts/to_h265 b/scripts/to_h265
--- a/scripts/to_h265
+++ b/scripts/to_h265
@@ -3,15 +3,15 @@
 # This script converts video files (.MOV) to H.265/HEVC format. It
 # automatically detects the platform (Linux or macOS) and adjusts the FFmpeg
 # settings accordingly:
-# 
+#
 #     Linux: Uses hevc_nvenc for hardware-accelerated encoding.
 #     macOS: Uses hevc_videotoolbox for hardware-accelerated encoding.
-# 
+#
 # If the platform is unsupported, the script will exit with an error.
 # Usage
-# 
+#
 #     ./to_h265.sh
-# 
+#
 #     The converted files will be saved in the h265 directory.
 
 AUDIO_CODECS_ACC=("libfdk_aac" "aac_at" "aac")
@@ -23,68 +23,67 @@ source "$(dirname "$0")/utils.sh"
 
 PLATFORM=$(uname -s)
 if [[ "$PLATFORM" == "Linux" ]]; then
-  VIDEO_HWACCEL="cuda"
-  VIDEO_CODEC="hevc_nvenc"
-  VIDEO_OPTIONS="-preset slow \
+	VIDEO_HWACCEL="cuda"
+	VIDEO_CODEC="hevc_nvenc"
+	VIDEO_OPTIONS="-preset slow \
     -qp 18 \
     -profile:v main10 \
     -pix_fmt p010le \
     -spatial_aq 1 \
     -temporal_aq 1"
 elif [[ "$PLATFORM" == "Darwin" ]]; then
-  VIDEO_HWACCEL="auto"
-  VIDEO_CODEC="hevc_videotoolbox"
-  VIDEO_OPTIONS="-tag:v hvc1 -q:v 65"
+	VIDEO_HWACCEL="auto"
+	VIDEO_CODEC="hevc_videotoolbox"
+	VIDEO_OPTIONS="-tag:v hvc1 -q:v 65"
 else
-  echo "Error: Unsupported platform - $PLATFORM"
-  exit 1
+	echo "Error: Unsupported platform - $PLATFORM"
+	exit 1
 fi
 
 if ! is_encoder_supported "$VIDEO_CODEC"; then
-    echo "Error: ${VIDEO_CODEC} not supported"
-    exit 1
+	echo "Error: ${VIDEO_CODEC} not supported"
+	exit 1
 fi
 
 SELECTED_AUDIO_CODEC=""
 for codec in "${AUDIO_CODECS_ACC[@]}"; do
-    if is_encoder_supported "$codec"; then
-        SELECTED_AUDIO_CODEC="$codec"
-        break
-    fi
+	if is_encoder_supported "$codec"; then
+		SELECTED_AUDIO_CODEC="$codec"
+		break
+	fi
 done
 
 if [ -z "$SELECTED_AUDIO_CODEC" ]; then
-    echo "Error: No supported AAC encoder found."
-    exit 1
+	echo "Error: No supported AAC encoder found."
+	exit 1
 fi
 
 total=$(find . -maxdepth 1 -type f -name "*.${IN_FORMAT}" | wc -l)
 i=1
 mkdir -p "${OUT_DIR}"
 
-for input_file in *.${IN_FORMAT}
-do
-  echo "${input_file} ${i}/${total}"
-  random_string=$(tr -dc 'a-zA-Z' </dev/urandom | fold -w 8 | head -n 1)
-  base_name="${input_file%.*}"
-  out_file_tmp="${OUT_DIR}/${base_name}${random_string}.tmp.${OUT_FORMAT}"
-  out_file="${OUT_DIR}/${base_name}.${OUT_FORMAT}"
+for input_file in *.${IN_FORMAT}; do
+	echo "${input_file} ${i}/${total}"
+	random_string=$(tr -dc 'a-zA-Z' </dev/urandom | fold -w 8 | head -n 1)
+	base_name="${input_file%.*}"
+	out_file_tmp="${OUT_DIR}/${base_name}${random_string}.tmp.${OUT_FORMAT}"
+	out_file="${OUT_DIR}/${base_name}.${OUT_FORMAT}"
 
-  if ! ffmpeg \
-        -nostdin \
-        -hwaccel ${VIDEO_HWACCEL} \
-        -i "${input_file}" \
-        -c:v ${VIDEO_CODEC} \
-        ${VIDEO_OPTIONS} \
-        -c:a ${SELECTED_AUDIO_CODEC} \
-        -b:a 320k \
-        -map_metadata 0 \
-        -loglevel warning \
-        "${out_file_tmp}"; then
-    echo "Error: ffmpeg failed"
-    exit 1
-  fi
+	if ! ffmpeg \
+		-nostdin \
+		-hwaccel ${VIDEO_HWACCEL} \
+		-i "${input_file}" \
+		-c:v ${VIDEO_CODEC} \
+		${VIDEO_OPTIONS} \
+		-c:a ${SELECTED_AUDIO_CODEC} \
+		-b:a 320k \
+		-map_metadata 0 \
+		-loglevel warning \
+		"${out_file_tmp}"; then
+		echo "Error: ffmpeg failed"
+		exit 1
+	fi
 
-  mv "${out_file_tmp}" "${out_file}"
-  ((i++))
+	mv "${out_file_tmp}" "${out_file}"
+	((i++))
 done
diff --git a/scripts/to_pcm b/scripts/to_pcm
--- a/scripts/to_pcm
+++ b/scripts/to_pcm
@@ -10,23 +10,22 @@ mkdir -p "${OUT_DIR}"
 total=$(find . -maxdepth 1 -type f -name '*${INPUT_FORMAT}' | wc -l)
 i=1
 
-for input_file in *.${INPUT_FORMAT}
-do
-  echo "${input_file} ${i}/${total}"
-  random_string=$(tr -dc 'a-zA-Z' </dev/urandom | fold -w 8 | head -n 1)
-  out_file_tmp="${OUT_DIR}/${input_file}${random_string}.tmp.${OUTPUT_FORMAT}"
-  out_file="${OUT_DIR}/${input_file}"
-  if ! ffmpeg \
-        -i "${input_file}" \
-        -c:v copy \
-        -c:a ${AUDIO_CODEC} \
-        -movflags faststart \
-        -threads 0 \
-        "${out_file_tmp}"; then
-    echo "Error: ffmpeg failed"
-    exit 1
-  fi
+for input_file in *.${INPUT_FORMAT}; do
+	echo "${input_file} ${i}/${total}"
+	random_string=$(tr -dc 'a-zA-Z' </dev/urandom | fold -w 8 | head -n 1)
+	out_file_tmp="${OUT_DIR}/${input_file}${random_string}.tmp.${OUTPUT_FORMAT}"
+	out_file="${OUT_DIR}/${input_file}"
+	if ! ffmpeg \
+		-i "${input_file}" \
+		-c:v copy \
+		-c:a ${AUDIO_CODEC} \
+		-movflags faststart \
+		-threads 0 \
+		"${out_file_tmp}"; then
+		echo "Error: ffmpeg failed"
+		exit 1
+	fi
 
-  mv "${out_file_tmp}" "${out_file%.$INPUT_FORMAT}.$OUTPUT_FORMAT"
-  ((i++))
+	mv "${out_file_tmp}" "${out_file%.$INPUT_FORMAT}.$OUTPUT_FORMAT"
+	((i++))
 done
diff --git a/scripts/yt_audio b/scripts/yt_audio
--- a/scripts/yt_audio
+++ b/scripts/yt_audio
@@ -8,14 +8,14 @@
 #
 # The flac file will be saved in ~/Music directory.
 
-if ! command -v yt-dlp &> /dev/null; then
-    echo "Error: yt-dlp is not installed. Please install it first."
-    exit 1
+if ! command -v yt-dlp &>/dev/null; then
+	echo "Error: yt-dlp is not installed. Please install it first."
+	exit 1
 fi
 
 if [ -z "$1" ]; then
-    echo "Usage: $0 <YouTube-link>"
-    exit 1
+	echo "Usage: $0 <YouTube-link>"
+	exit 1
 fi
 
 yt-dlp "$1" -f ba --extract-audio --audio-format flac -o "$HOME/Music/%(title)s.%(ext)s"
